### ISSUE TITLE
Crash, help me.

### ISSUE THREAD

**Issue by Barrery** [MinecrafterJPN/ChestShop#10]
![_3wmopcall4](https://cloud.githubusercontent.com/assets/11139926/6316172/b986a85e-ba36-11e4-8103-afa948717f2f.jpg)
When someone trying to buy anything, server stops with this error.
Im using last beta build, and PocketMoney ChestShop PoketJobs

**Comment by MinecrafterJPN** [comment]
Sorry for the late reply.
Use PocketMoney latest ver.
