### ISSUE TITLE
サーバーがクラッシュします。

### ISSUE THREAD

**Issue by FUGAMARU** [MinecrafterJPN/ChestShop#11]
最近よく、
Fatal error: Call to a member function getSize() on null in phar://C:/Users/Owner/Desktop/3rdFUGAMARU-SERVER/plugins/ChestShop_v2.0.1.phar/src/ChestShop/EventListener.php on line 57

Call Stack:
    0.0024     128672   1. {main}() C:\Users\Owner\Desktop\3rdFUGAMARU-SERVER\src\pocketmine\PocketMine.php:0
    0.2604     243960   2. pocketmine\Server->__construct() C:\Users\Owner\Desktop\3rdFUGAMARU-SERVER\src\pocketmine\PocketMine.php:437
    6.0869   13642072   3. pocketmine\Server->start() C:\Users\Owner\Desktop\3rdFUGAMARU-SERVER\src\pocketmine\Server.php:1758
    6.1001   13679368   4. pocketmine\Server->tickProcessor() C:\Users\Owner\Desktop\3rdFUGAMARU-SERVER\src\pocketmine\Server.php:2071
 1868.7278  233824424   5. pocketmine\Server->tick() C:\Users\Owner\Desktop\3rdFUGAMARU-SERVER\src\pocketmine\Server.php:2195
 1868.7279  233824488   6. pocketmine\network\RakLibInterface->process() C:\Users\Owner\Desktop\3rdFUGAMARU-SERVER\src\pocketmine\Server.php:2301
 1868.7362  233825024   7. raklib\server\ServerHandler->handlePacket() C:\Users\Owner\Desktop\3rdFUGAMARU-SERVER\src\pocketmine\network\RakLibInterface.php:138
 1868.7363  233826008   8. pocketmine\network\RakLibInterface->handleEncapsulated() C:\Users\Owner\Desktop\3rdFUGAMARU-SERVER\src\raklib\server\ServerHandler.php:92
 1868.7364  233826768   9. pocketmine\Player->handleDataPacket() C:\Users\Owner\Desktop\3rdFUGAMARU-SERVER\src\pocketmine\network\RakLibInterface.php:191
 1868.7365  233827376  10. pocketmine\level\Level->useItemOn() C:\Users\Owner\Desktop\3rdFUGAMARU-SERVER\src\pocketmine\Player.php:1659
 1868.7367  233827856  11. pocketmine\plugin\PluginManager->callEvent() C:\Users\Owner\Desktop\3rdFUGAMARU-SERVER\src\pocketmine\level\Level.php:1325
 1868.7370  233827856  12. pocketmine\plugin\RegisteredListener->callEvent() C:\Users\Owner\Desktop\3rdFUGAMARU-SERVER\src\pocketmine\plugin\PluginManager.php:670
 1868.7370  233827856  13. pocketmine\plugin\MethodEventExecutor->execute() C:\Users\Owner\Desktop\3rdFUGAMARU-SERVER\src\pocketmine\plugin\RegisteredListener.php:96
 1868.7370  233827856  14. ChestShop\EventListener->onPlayerInteract() C:\Users\Owner\Desktop\3rdFUGAMARU-SERVER\src\pocketmine\plugin\MethodEventExecutor.php:36
という理由でサーバーがクラッシュします。PocetMine-MP Softの1.4.1(dev-226)を使用しています。ChestShopのバージョンは2.0.1です。OSはWindows8.1です。
クラッシュレポート→https://www.dropbox.com/s/o7r42nnxg26kjwy/CrashDump_Sun_Mar_15-17.54.27-CST_2015.log?dl=0

**Comment by MinecrafterJPN** [comment]
報告有り難うございます。
- クラッシュはShop購入時に発生しますか？
-  マルチワールドを利用していますか？

**Comment by FUGAMARU** [comment]
返信有難うございます。

SHOP購入時にはクラッシュしませんでした。
マルチワールドを利用しています。

よろしくお願いいたします。

**Comment by MinecrafterJPN** [comment]
@FUGAMARU クラッシュが発生するタイミングなどはわかりますか？

**Comment by FUGAMARU** [comment]
タイミングは把握していません。

**Comment by MinecrafterJPN** [comment]
@FUGAMARU 例えば、プレイヤーが誰も居ない時でもクラッシュしますか？

**Comment by FUGAMARU** [comment]
誰も居ない時にはクラッシュしません。また、いつも(と言っても出ない時もある)画像のようにエラーがコンソールに表示されています。画像→https://www.dropbox.com/s/h2w69728fjnvvnh/amarecco0062.PNG?dl=0

**Comment by MinecrafterJPN** [comment]
@FUGAMARU ありがとうございます。
調査してみます

**Comment by FUGAMARU** [comment]
よろしくお願い致します。

**Comment by MinecrafterJPN** [comment]
@FUGAMARU 原因判明しました。ChestShopのバグではなくPocketMoneyのバグです。
現在、GitHubの方では修正コミットを打っていますがフォーラムではまだ公開していません。
すぐに申請しますので少々お待ちください。

ちなみにバグの原因ですが、ChestShopでの取引時にショップのオーナーがログインしていない際にPocketMoneyのAPIに不正な引数が渡されエラーを吐くといったものです。

**Comment by FUGAMARU** [comment]
調査お疲れ様でした。また、迅速な対応誠に感謝しています。これからも頑張ってください！
