### ISSUE TITLE
Error on server startup: Unable to open database...

### ISSUE THREAD

**Issue by morrowc** [MinecrafterJPN/ChestShop#8]
[CRITICAL] Exception: "Unable to open database: unable to open database file" (EXCEPTION) in "/ChestShop.phar/src/ChestShop/DatabaseManager" at line 16

with server (MCPE) version:
  00:49:28 [INFO] This server is running PocketMine-MP version 1.4-916 "絶好(Zekkou)ケーキ(Cake)" (API 1.10.0)

not clear from the github repository where this file should be, looking at your source:
(https://github.com/MinecrafterJPN/ChestShop/blob/master/src/ChestShop/DatabaseManager.php#L16)
class DatabaseManager
{
    private $database;
    /**
     * @param string $path
     */
    public function __construct($path)
    {
        $this->database = new \SQLite3($path);

which is called from:
(https://github.com/MinecrafterJPN/ChestShop/blob/master/src/ChestShop/ChestShop.php#L23)
  $this->getServer()->getPluginManager()->registerEvents(new EventListener($this, new DatabaseManager($this->getDataFolder() . "ChestShop.sqlite3")), $this);

Oh, so... you're not checking to see if the directory exists before attempting to open a file in that directory. I'll attempt a fix, though I admit I don't know how to make the phar file or probably properly test the change... pull request coming shortly.

**Comment by morrowc** [comment]
Actually I suck and I can't make a pull request right now, but:

diff --git a/src/ChestShop/DatabaseManager.php b/src/ChestShop/DatabaseManager.p
index 46047c1..5f43ade 100644
--- a/src/ChestShop/DatabaseManager.php
+++ b/src/ChestShop/DatabaseManager.php
@@ -8,8 +8,15 @@ class DatabaseManager
 {
     private $database;
 
+    /**
+     * @param string $path
+     */
     public function __construct($path)
     {
+        $dir = dirname($path);
+        if (!is_dir($dir)) {
+              mkdir($dir);
+        }


that's the relevant change.

**Comment by MinecrafterJPN** [comment]
Thank you. I'll fix it.
